using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace RestCodeGenerator;

/// <summary>
/// Renders a parsed swagger document (plus an API name) into the complete generated
/// component: one self-contained `.cs` source text and the fallback `.csproj` text.
/// The emitted text follows the Task 4 template in
/// project-docs/plans/2026-08-31-swagger-rest-codegen.md — that template is the contract.
/// The template's verbatim blocks are kept as raw-string constants below; only the
/// endpoint methods, fields, and header comment are computed per document.
/// </summary>
public static class ComponentRenderer
{
    /// <param name="designerComponent">When true, the class derives from
    /// <c>System.ComponentModel.Component</c> and follows the Dispose pattern: the
    /// HttpClient becomes instance-level so Dispose can release it (Robot Studio
    /// disposes tray components on teardown). Default false keeps Script-component
    /// paste-in output with the shared static client.</param>
    public static (string FileNameBase, string Source, string Project) Render(ApiSpec doc, string apiName, bool designerComponent = false)
    {
        var root = MethodNameMapper.Pascalize(apiName) ?? "Api";
        var className = root + "RestUtils";
        var @namespace = root + "RestAutomation";

        // Scheme-conditional helpers are emitted only when the spec declares that kind.
        var hasApiKeyHeader = doc.SecuritySchemes.Any(s => s.Kind == "apiKeyHeader");
        var hasApiKeyQuery = doc.SecuritySchemes.Any(s => s.Kind == "apiKeyQuery");
        var hasOAuth2 = doc.SecuritySchemes.Any(s => s.Kind == "oauth2ClientCredentials");
        var unsupportedSchemes = doc.SecuritySchemes.Where(s => s.Kind == "unsupported").ToList();

        var sb = new StringBuilder();
        AppendFileHeader(sb, doc, unsupportedSchemes);
        AppendNamespaceAndClass(sb, doc, @namespace, className, designerComponent);
        AppendFields(sb, doc, hasApiKeyHeader, hasApiKeyQuery, hasOAuth2, designerComponent);
        sb.AppendLine();
        sb.AppendLine(DesignTimeProperties(hasApiKeyHeader, hasApiKeyQuery, hasOAuth2));
        sb.AppendLine();
        sb.AppendLine(AlwaysPresentHelpers(hasApiKeyHeader, hasApiKeyQuery, hasOAuth2));
        var usesTypedBody = AppendEndpointMethods(sb, doc);
        AppendPrivateCore(sb, hasApiKeyHeader, hasApiKeyQuery, hasOAuth2, usesTypedBody, designerComponent);
        if (designerComponent) sb.AppendLine("\n" + DisposePattern);
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return (className, sb.ToString(), FallbackProject.Replace("%Namespace%", @namespace));
    }

    // ---- Header comment / class declaration / fields ----

    private static void AppendFileHeader(StringBuilder sb, ApiSpec doc, List<ApiSecurityScheme> unsupported)
    {
        sb.Append("// <auto-generated>Generated by RestCodeGenerator from ")
          .Append(doc.Title ?? "Api").Append(" v").Append(doc.Version ?? "1.0.0")
          .AppendLine(". Do not edit.</auto-generated>");
        sb.AppendLine("// Skipped operations (non-JSON bodies are not supported):");
        if (doc.SkippedOperations.Count == 0)
            sb.AppendLine("//   (none)");
        else
            foreach (var skipped in doc.SkippedOperations)
                sb.AppendLine("//   " + skipped);
        if (unsupported.Count > 0)
        {
            sb.AppendLine("// Unsupported authentication schemes (no helper generated — use SetBearerAuthentication");
            sb.AppendLine("//   or SetCustomAuthentication with a caller-managed token instead):");
            foreach (var scheme in unsupported)
                sb.AppendLine("//   " + scheme.Name);
        }
        sb.AppendLine();
    }

    private static void AppendNamespaceAndClass(
        StringBuilder sb, ApiSpec doc, string @namespace, string className, bool designerComponent)
    {
        var title = doc.Title ?? "Api";
        var version = doc.Version ?? "1.0.0";
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Net.Http;");
        sb.AppendLine("using System.Net.Http.Headers;");
        sb.AppendLine("using System.Text;");
        sb.AppendLine();
        sb.AppendLine("namespace " + @namespace);
        sb.AppendLine("{");
        // API metadata from the swagger `info` object. Class-level docs/attribute are
        // mode-independent, so this emission is identical in default and designerComponent
        // modes; only the base type below differs between them.
        AppendClassDocs(sb, doc, title, version);
        AppendClassDescriptionAttribute(sb, doc, title, version);
        sb.AppendLine("    public class " + className +
                      (designerComponent ? " : System.ComponentModel.Component" : ""));
        sb.AppendLine("    {");
    }

    /// <summary>
    /// Emits the class-level XML doc comment carrying the swagger <c>info</c> metadata:
    /// the summary pairs the title with the version, then the description (flattened
    /// with the same normalize helper as method summaries, word-wrapped into /// lines
    /// when long). <c>&lt;remarks&gt;</c> carries the terms-of-service, contact, and
    /// license lines — each omitted entirely when its entity is absent from the spec
    /// (a null field never leaves an empty line or placeholder), and its content is
    /// XML-escaped via <see cref="Xml"/> (description/contact text may contain &lt;).
    /// </summary>
    private static void AppendClassDocs(StringBuilder sb, ApiSpec doc, string title, string version)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// " + Xml(title) + " (version " + Xml(version) + ").");
        foreach (var line in WrapWords(Flatten(doc.Description), 110))
            sb.AppendLine("    /// " + Xml(line));
        sb.AppendLine("    /// One method per operation in the source swagger file. Response bodies are");
        sb.AppendLine("    /// returned as raw JSON strings; parse them with Robot Studio's built-in JSON");
        sb.AppendLine("    /// methods. Every public method follows the Never-Throws Standard: success");
        sb.AppendLine("    /// returns true with message null; failure returns false with a reason.");
        sb.AppendLine("    /// Pass \"\" for any optional string parameter to omit it. A request body whose");
        sb.AppendLine("    /// schema names fields is broken into one typed parameter per field and assembled");
        sb.AppendLine("    /// into JSON automatically; a body with no named fields instead takes a single");
        sb.AppendLine("    /// bodyJson string parameter to pass through as-is.");
        sb.AppendLine("    /// BaseUrl, TimeoutSeconds, and any scheme-specific credentials are public");
        sb.AppendLine("    /// properties — set them (design time or at the start of a run) before calling");
        sb.AppendLine("    /// an endpoint method.");
        sb.AppendLine("    /// </summary>");
        var remarks = ClassRemarksLines(doc);
        if (remarks.Count > 0)
        {
            sb.AppendLine("    /// <remarks>");
            foreach (var line in remarks)
                sb.AppendLine("    /// " + line);   // pre-escaped XML
            sb.AppendLine("    /// </remarks>");
        }
    }

    /// <summary>The <c>&lt;remarks&gt;</c> content lines for the class docs: TOS, contact,
    /// and license, each present only when the spec carries actual values. Contact parts
    /// are individually optional — the "Contact:" line appears only when any part exists.</summary>
    private static List<string> ClassRemarksLines(ApiSpec doc)
    {
        var lines = new List<string>();
        if (!string.IsNullOrWhiteSpace(doc.TermsOfService))
            lines.Add("<para>Terms of service: " + Xml(doc.TermsOfService) + "</para>");
        var contact = new List<string>();
        if (!string.IsNullOrWhiteSpace(doc.ContactName)) contact.Add(Xml(doc.ContactName));
        if (!string.IsNullOrWhiteSpace(doc.ContactEmail)) contact.Add("&lt;" + Xml(doc.ContactEmail) + "&gt;");
        if (!string.IsNullOrWhiteSpace(doc.ContactUrl)) contact.Add("(" + Xml(doc.ContactUrl) + ")");
        if (contact.Count > 0)
            lines.Add("<para>Contact: " + string.Join(" ", contact) + "</para>");
        if (!string.IsNullOrWhiteSpace(doc.LicenseName) || !string.IsNullOrWhiteSpace(doc.LicenseUrl))
        {
            var line = "<para>License: ";
            if (!string.IsNullOrWhiteSpace(doc.LicenseName))
                line += Xml(doc.LicenseName);
            if (!string.IsNullOrWhiteSpace(doc.LicenseUrl))
                line += (line.EndsWith(": ", System.StringComparison.Ordinal) ? "" : " ") +
                        "(" + Xml(doc.LicenseUrl) + ")";
            lines.Add(line + "</para>");
        }
        return lines;
    }

    /// <summary>
    /// The class-level designer-visible summary: "&lt;Title&gt; (version &lt;Version&gt;) - &lt;first
    /// sentence of the flattened description&gt;". The first-sentence rule: the whole
    /// description when at most 120 characters, otherwise the text up to and including
    /// the first ". " sentence break (or the whole text when it has no sentence break).
    /// Deterministic. Omitted only when the spec carries neither a title nor a description.
    /// </summary>
    private static void AppendClassDescriptionAttribute(StringBuilder sb, ApiSpec doc, string title, string version)
    {
        var description = Flatten(doc.Description);
        if (doc.Title is null && description.Length == 0)
            return;
        var sentence = FirstSentence(description);
        sb.AppendLine("    [System.ComponentModel.Description(" +
                      Lit(title + " (version " + version + ")" +
                          (sentence.Length > 0 ? " - " + sentence : "")) + ")]");
    }

    /// <summary>The attribute's description excerpt — see <see cref="AppendClassDescriptionAttribute"/>.</summary>
    private static string FirstSentence(string flattened)
    {
        if (flattened.Length <= 120) return flattened;
        var end = flattened.IndexOf(". ", System.StringComparison.Ordinal);
        return end > 0 ? flattened[..end] + "." : flattened;
    }

    private static void AppendFields(
        StringBuilder sb, ApiSpec doc, bool hasApiKeyHeader, bool hasApiKeyQuery, bool hasOAuth2,
        bool designerComponent)
    {
        if (string.IsNullOrEmpty(doc.DefaultBaseUrl))
            sb.AppendLine("        private string _baseUrl = \"\";");
        else
            sb.AppendLine("        private string _baseUrl = " + Lit(doc.DefaultBaseUrl) + ";   // prefilled from the spec's base URL");
        sb.AppendLine("        private string _authorizationHeader = \"\";");
        if (hasApiKeyHeader)
        {
            sb.AppendLine("        private string _apiKeyHeaderName = \"\";      // API key sent as a named header on every call");
            sb.AppendLine("        private string _apiKeyHeaderValue = \"\";");
        }
        if (hasApiKeyQuery)
        {
            sb.AppendLine("        private string _apiKeyQueryName = \"\";       // API key appended to the query string of every call");
            sb.AppendLine("        private string _apiKeyQueryValue = \"\";");
        }
        if (hasOAuth2)
        {
            sb.AppendLine("        private string _oauthClientId = \"\";         // OAuth2 client-credentials configuration");
            sb.AppendLine("        private string _oauthClientSecret = \"\";");
            sb.AppendLine("        private string _oauthTokenUrl = \"\";");
            sb.AppendLine("        private string _oauthScope = \"\";");
            sb.AppendLine("        private string _oauthAccessToken = \"\";");
            sb.AppendLine("        private System.DateTime _oauthTokenExpiresAtUtc = System.DateTime.MinValue;");
        }
        sb.AppendLine("        private int _lastStatusCode;");
        sb.AppendLine("        private int _timeoutSeconds = 30;");
        if (designerComponent)
        {
            // instance-level client so the Dispose pattern below has something real to release
            sb.AppendLine("        private readonly HttpClient _httpClient = new HttpClient();");
        }
        else
        {
            sb.AppendLine("        private static readonly HttpClient _client = new HttpClient();");
        }
    }

    // ---- Always-present public helpers ----

    /// <summary>
    /// The helpers every generated component carries, regardless of declared schemes.
    /// The //[[…]] markers inside ClearAuthentication become a clear line only for the
    /// scheme-conditional fields that exist in the emitted file (dropped otherwise, so
    /// ClearAuthentication never references a field that was not emitted).
    /// </summary>
    private static string AlwaysPresentHelpers(bool hasApiKeyHeader, bool hasApiKeyQuery, bool hasOAuth2)
    {
        // Markers are matched WITHOUT a trailing newline so the replacement is CRLF-safe
        // (raw strings preserve the source file's line endings). When the scheme is not
        // declared, a comment line remains instead of a live statement.
        return AlwaysPresentHelpersCore
            .Replace("            //[[API_KEY_HEADER_CLEAR]]", hasApiKeyHeader
                ? "            _apiKeyHeaderName = \"\"; _apiKeyHeaderValue = \"\";"
                : "            // (no api-key-header scheme declared)")
            .Replace("            //[[API_KEY_QUERY_CLEAR]]", hasApiKeyQuery
                ? "            _apiKeyQueryName = \"\"; _apiKeyQueryValue = \"\";"
                : "            // (no api-key-query scheme declared)")
            .Replace("            //[[OAUTH_CLEAR]]", hasOAuth2
                ? "            _oauthAccessToken = \"\";"
                : "            // (no client-credentials oauth2 scheme declared)");
    }

    private const string AlwaysPresentHelpersCore =
"""
        // ---- Always-present helpers (never throws) ----

        /// <summary>Sets the Authorization header to "Bearer &lt;token&gt;". Never throws.</summary>
        public bool SetBearerAuthentication(string token, out string message)
        {
            if (string.IsNullOrWhiteSpace(token)) { message = "SetBearerAuthentication: token must be non-empty."; return false; }
            _authorizationHeader = "Bearer " + token.Trim();
            message = null; return true;
        }

        /// <summary>Sets the Authorization header to HTTP Basic. Never throws.</summary>
        public bool SetBasicAuthentication(string username, string password, out string message)
        {
            try
            {
                _authorizationHeader = "Basic " + Convert.ToBase64String(Encoding.UTF8.GetBytes((username ?? "") + ":" + (password ?? "")));
                message = null; return true;
            }
            catch (Exception ex)
            {
                _authorizationHeader = "";
                message = "SetBasicAuthentication: " + ex.Message; return false;
            }
        }

        /// <summary>Sets the Authorization header to an explicit value (e.g. an API key that arrives as the Authorization value). Never throws.</summary>
        public bool SetCustomAuthentication(string headerValue, out string message)
        {
            if (string.IsNullOrWhiteSpace(headerValue)) { message = "SetCustomAuthentication: headerValue must be non-empty."; return false; }
            _authorizationHeader = headerValue.Trim();
            message = null; return true;
        }

        /// <summary>Clears all configured authentication (Authorization header, API keys, cached OAuth2 token — the client-credentials configuration itself is kept). Never throws.</summary>
        public bool ClearAuthentication(out string message)
        {
            _authorizationHeader = "";
            //[[API_KEY_HEADER_CLEAR]]
            //[[API_KEY_QUERY_CLEAR]]
            //[[OAUTH_CLEAR]]
            message = null; return true;
        }

        /// <summary>The HTTP status code of the most recent endpoint call; 0 before the first call. Never throws.</summary>
        public int LastStatusCode
        {
            get { return _lastStatusCode; }
        }
""";

    // ---- Design-time properties ----

    /// <summary>
    /// Public properties for the static, usually-known-at-design-time configuration:
    /// base URL, timeout, and (when declared) the scheme-conditional credential fields.
    /// These are plain get/set — Robot Studio's property grid can set them at design
    /// time without a workflow step — so they clamp/normalize silently instead of
    /// returning a bool + message the way the runtime auth-mode helpers do.
    /// </summary>
    private static string DesignTimeProperties(bool hasApiKeyHeader, bool hasApiKeyQuery, bool hasOAuth2)
    {
        var sb = new StringBuilder();
        sb.Append(BaseUrlAndTimeoutProperties);
        if (hasApiKeyHeader) sb.Append("\n" + ApiKeyHeaderProperties);
        if (hasApiKeyQuery) sb.Append("\n" + ApiKeyQueryProperties);
        if (hasOAuth2) sb.Append("\n" + OAuth2Properties);
        return sb.ToString();
    }

    private const string BaseUrlAndTimeoutProperties =
"""
        // ---- Design-time properties (never throw; set directly, no out-message) ----

        /// <summary>The base URL prefixed to every request path. Required when the source
        /// spec had no concrete base URL (e.g. a templated OA3 server) — the class doc
        /// comment then flags it as mandatory. Trailing slashes are trimmed. Never throws.</summary>
        [System.ComponentModel.Description("The base URL prefixed to every request path.")]
        public string BaseUrl
        {
            get { return _baseUrl; }
            set { _baseUrl = string.IsNullOrWhiteSpace(value) ? "" : value.TrimEnd('/'); }
        }

        /// <summary>Request timeout in seconds; silently clamped to 1–600 (default 30). Never throws.</summary>
        [System.ComponentModel.Description("Request timeout in seconds (1-600, default 30).")]
        public int TimeoutSeconds
        {
            get { return _timeoutSeconds; }
            set { _timeoutSeconds = value < 1 ? 1 : (value > 600 ? 600 : value); }
        }
""";

    /// <summary>Emitted when the spec declares an apiKey scheme with `in: header`.</summary>
    private const string ApiKeyHeaderProperties =
"""
        /// <summary>Name of the header carrying the API key sent on every call. Never throws.</summary>
        [System.ComponentModel.Description("Name of the header carrying the API key sent on every call.")]
        public string ApiKeyHeaderName
        {
            get { return _apiKeyHeaderName; }
            set { _apiKeyHeaderName = value ?? ""; }
        }

        /// <summary>Value of the API key sent as that named header on every call. Never throws.</summary>
        [System.ComponentModel.Description("Value of the API key sent as a named header on every call.")]
        public string ApiKeyHeaderValue
        {
            get { return _apiKeyHeaderValue; }
            set { _apiKeyHeaderValue = value ?? ""; }
        }
""";

    /// <summary>Emitted when the spec declares an apiKey scheme with `in: query`.</summary>
    private const string ApiKeyQueryProperties =
"""
        /// <summary>Name of the query-string parameter carrying the API key appended to every call. Never throws.</summary>
        [System.ComponentModel.Description("Name of the query parameter carrying the API key appended to every call.")]
        public string ApiKeyQueryName
        {
            get { return _apiKeyQueryName; }
            set { _apiKeyQueryName = value ?? ""; }
        }

        /// <summary>Value of the API key appended to the query string of every call. Never throws.</summary>
        [System.ComponentModel.Description("Value of the API key appended to the query string of every call.")]
        public string ApiKeyQueryValue
        {
            get { return _apiKeyQueryValue; }
            set { _apiKeyQueryValue = value ?? ""; }
        }
""";

    /// <summary>Emitted when the spec declares an oauth2 scheme with the client-credentials (or "application") flow.</summary>
    private const string OAuth2Properties =
"""
        /// <summary>OAuth2 client-credentials client ID. Setting it invalidates any cached access
        /// token, so the next call re-authenticates against the token endpoint. Never throws.</summary>
        [System.ComponentModel.Description("OAuth2 client-credentials client ID.")]
        public string OAuthClientId
        {
            get { return _oauthClientId; }
            set { _oauthClientId = value ?? ""; InvalidateOAuthToken(); }
        }

        /// <summary>OAuth2 client-credentials client secret. Setting it invalidates any cached access
        /// token, so the next call re-authenticates against the token endpoint. Never throws.</summary>
        [System.ComponentModel.Description("OAuth2 client-credentials client secret.")]
        public string OAuthClientSecret
        {
            get { return _oauthClientSecret; }
            set { _oauthClientSecret = value ?? ""; InvalidateOAuthToken(); }
        }

        /// <summary>OAuth2 token endpoint URL. Setting it invalidates any cached access token, so
        /// the next call re-authenticates against the (new) token endpoint. Never throws.</summary>
        [System.ComponentModel.Description("OAuth2 token endpoint URL.")]
        public string OAuthTokenUrl
        {
            get { return _oauthTokenUrl; }
            set { _oauthTokenUrl = value ?? ""; InvalidateOAuthToken(); }
        }

        /// <summary>OAuth2 client-credentials scope (optional — required by some providers, e.g.
        /// Microsoft Entra ID's v2.0 token endpoint, which needs a value like
        /// "https://graph.microsoft.com/.default"). Left blank, no scope parameter is sent.
        /// Setting it invalidates any cached access token. Never throws.</summary>
        [System.ComponentModel.Description("OAuth2 client-credentials scope (optional; required by some providers, e.g. Microsoft Entra ID).")]
        public string OAuthScope
        {
            get { return _oauthScope; }
            set { _oauthScope = value ?? ""; InvalidateOAuthToken(); }
        }

        private void InvalidateOAuthToken()
        {
            _oauthAccessToken = "";
            _oauthTokenExpiresAtUtc = System.DateTime.MinValue;
        }
""";

    // ---- Endpoint methods (one per modeled swagger operation) ----

    /// <summary>Returns true when at least one emitted method flattened its body into typed
    /// parameters — the caller uses this to decide whether the JsonString/JsonNumber/JsonBool/
    /// JsonArray runtime helpers are needed at all.</summary>
    private static bool AppendEndpointMethods(StringBuilder sb, ApiSpec doc)
    {
        var names = MethodNameMapper.Map(doc.Operations);
        sb.AppendLine();
        sb.AppendLine("        // ---- Endpoint methods (one per usable swagger operation) ----");
        var usesTypedBody = false;
        foreach (var op in doc.Operations)
            usesTypedBody |= AppendEndpointMethod(sb, op, names[op]);
        return usesTypedBody;
    }

    /// <summary>
    /// Emits one endpoint method: path params become chained <c>.Replace("{name}", …)</c>
    /// substitutions, query params a <c>BuildQuery().Add(…)</c> chain, header params a
    /// <c>WithHeader(…)</c> chain, and the body either flattens into typed parameters
    /// reassembled into a local <c>bodyJson</c> (see <see cref="TryFlattenBody"/>) or, when
    /// that isn't possible, falls back to a raw <c>bodyJson</c> string parameter. All inputs
    /// are designers' strings; the never-throw HTTP core does the rest. Returns true when the
    /// body was flattened into typed parameters (the caller uses this to gate the JSON runtime helpers).
    /// </summary>
    private static bool AppendEndpointMethod(StringBuilder sb, ApiOperation op, string name)
    {
        var used = new HashSet<string>();
        // Reserved up front: a flattened body assembles into a local also named "bodyJson" (and
        // a non-flattened body's own parameter is literally called that) — reserving it here
        // means a same-named path/query/header/body-field param gets suffixed instead of colliding.
        if (op.HasBody) used.Add("bodyJson");
        var paths = op.PathParams.Select(p => (Original: p.Name, Param: ParamName(p, used))).ToList();
        var queries = op.QueryParams.Select(p => (Original: p.Name, Param: ParamName(p, used))).ToList();
        var headers = op.HeaderParams.Select(p => (Original: p.Name, Param: ParamName(p, used))).ToList();

        // A multi-line swagger summary must be flattened to a single line here, before it
        // feeds either the XML doc comment (a raw "\n" would emit a continuation line
        // without "///") or the Description attribute (Lit also escapes, per defense in depth).
        var summary = Flatten(op.Summary);
        if (summary.Length == 0)
            summary = "Performs the " + op.HttpMethod + " request on " + op.Path + ".";

        var flattenedBody = op.HasBody ? TryFlattenBody(op, used) : null;
        var bodyNote = flattenedBody != null && SchemaContainsArray(op.BodySchema!)
            ? " Repeated (array) body fields are capped at a fixed number of slots; leave every parameter in an unused slot empty (\"\") to omit that entry."
            : "";

        sb.AppendLine();
        sb.AppendLine("        /// <summary>" + Xml(summary) + bodyNote +
                      " Returns true if the HTTP call completed; check statusCode for 4xx/5xx. Never throws.</summary>");
        sb.AppendLine("        [System.ComponentModel.Description(" +
                      Lit(summary + " (" + op.HttpMethod + " " + op.Path + ")") + ")]");

        var signature = new List<string>();
        signature.AddRange(paths.Select(p => "string " + p.Param));
        signature.AddRange(queries.Select(p => "string " + p.Param));
        signature.AddRange(headers.Select(p => "string " + p.Param));
        if (flattenedBody is { } fb)
            signature.AddRange(fb.Params.Select(p => "string " + p));
        else if (op.HasBody)
            signature.Add("string bodyJson");
        signature.Add("out string responseJson");
        signature.Add("out int statusCode");
        signature.Add("out string message");

        sb.AppendLine("        public bool " + name + "(" + string.Join(", ", signature) + ")");
        sb.AppendLine("        {");
        if (flattenedBody is { } body)
            sb.AppendLine("            var bodyJson = " + body.Expr + ";");

        sb.Append("            var path = " + Lit(op.Path));
        foreach (var p in paths)
            sb.Append(".Replace(" + Lit("{" + p.Original + "}") + ", Uri.EscapeDataString(" + p.Param + " ?? \"\"))");
        sb.AppendLine(";");

        if (queries.Count == 1)
        {
            sb.AppendLine("            var query = BuildQuery().Add(" + Lit(queries[0].Original) + ", " + queries[0].Param + ").ToString();");
        }
        else if (queries.Count > 1)
        {
            sb.AppendLine("            var query = BuildQuery()");
            foreach (var q in queries)
                sb.AppendLine("                .Add(" + Lit(q.Original) + ", " + q.Param + ")");
            sb.AppendLine("                .ToString();");
        }

        var queryArg = queries.Count > 0 ? "query" : "BuildQuery().ToString()";
        var bodyArg = op.HasBody ? "bodyJson" : "null";
        sb.Append("            return Send(" + Lit(op.HttpMethod) + ", path, " + queryArg + ", " + bodyArg + ", ");
        if (headers.Count == 0)
        {
            sb.AppendLine("NewHeaders(), out responseJson, out statusCode, out message);");
        }
        else if (headers.Count == 1)
        {
            sb.AppendLine("NewHeaders().WithHeader(" + Lit(headers[0].Original) + ", " + headers[0].Param + "), out responseJson, out statusCode, out message);");
        }
        else
        {
            sb.AppendLine("NewHeaders()");
            for (var i = 0; i < headers.Count; i++)
            {
                var line = "                .WithHeader(" + Lit(headers[i].Original) + ", " + headers[i].Param + ")";
                sb.AppendLine(i == headers.Count - 1
                    ? line + ", out responseJson, out statusCode, out message);"
                    : line);
            }
        }
        sb.AppendLine("        }");
        return flattenedBody != null;
    }

    /// <summary>Camelizes a swagger parameter name into a C# identifier, unique within one method.</summary>
    private static string ParamName(ApiParameter p, HashSet<string> used) => UniqueName(p.Name, used);

    /// <summary>Camelizes a suggested name into a C# identifier, unique within one method
    /// (numeric suffix on collision — including collisions with path/query/header param names,
    /// since body-flattened parameters share the same signature and the same <c>used</c> set).</summary>
    private static string UniqueName(string suggested, HashSet<string> used)
    {
        var pascal = MethodNameMapper.Pascalize(suggested) ?? "Param";
        var name = char.ToLowerInvariant(pascal[0]) + pascal[1..];
        var candidate = name;
        var suffix = 2;
        while (!used.Add(candidate))
            candidate = name + suffix++;
        return candidate;
    }

    // ---- Request body flattening (typed parameters, assembled into JSON at runtime) ----

    /// <summary>
    /// Flattens a body's <see cref="ApiSchema"/> tree into typed method parameters plus a
    /// runtime expression that reassembles them into a JSON literal. Only usable when the body
    /// is a top-level JSON object with at least one flattenable property — a free-form object,
    /// a non-object body, or a schema the parser couldn't resolve all fall back to the original
    /// raw <c>bodyJson</c> string parameter (returns null).
    /// </summary>
    private static (IReadOnlyList<string> Params, string Expr)? TryFlattenBody(ApiOperation op, HashSet<string> used)
    {
        if (op.BodySchema is not { JsonType: "object" } schema || schema.Properties.Count == 0)
            return null;
        var (expr, leafParams) = BuildBodyNode(schema, "", "", used);
        return leafParams.Count == 0 ? null : (leafParams, expr);
    }

    /// <summary>
    /// Recursively emits a runtime C# expression that evaluates to the JSON text for one schema
    /// node, and returns the leaf parameter names it introduced (in emission order — this both
    /// becomes the flattened method signature and lets an enclosing array slot detect whether it
    /// was actually filled in). <paramref name="nameHint"/> is the property key to use when this
    /// node turns out to be a scalar leaf; it threads unchanged through arrays (their item schema
    /// has no key of its own) and is reset to each property's own name inside an object.
    /// <paramref name="arraySlotSuffix"/> is appended to a leaf's name so each repeated array slot
    /// gets its own parameter (e.g. "cardNumber1".."cardNumber5").
    /// </summary>
    private static (string Expr, List<string> LeafParams) BuildBodyNode(
        ApiSchema schema, string nameHint, string arraySlotSuffix, HashSet<string> used)
    {
        switch (schema.JsonType)
        {
            case "object":
            {
                if (schema.Properties.Count == 0)
                    return ("\"{}\"", new List<string>());
                var parts = new List<string>();
                var leafParams = new List<string>();
                foreach (var prop in schema.Properties)
                {
                    var (valueExpr, propLeafParams) = BuildBodyNode(prop.Schema, prop.Name, arraySlotSuffix, used);
                    parts.Add(JsonKeyPrefixLit(prop.Name) + " + " + valueExpr);
                    leafParams.AddRange(propLeafParams);
                }
                return ("(\"{\" + " + string.Join(" + \",\" + ", parts) + " + \"}\")", leafParams);
            }
            case "array":
            {
                var slots = new List<string>();
                var leafParams = new List<string>();
                for (var i = 1; i <= schema.MaxItems; i++)
                {
                    var (itemExpr, itemLeafParams) = BuildBodyNode(schema.Items!, nameHint, arraySlotSuffix + i, used);
                    var presence = itemLeafParams.Count == 0
                        ? "false"
                        : string.Join(" || ", itemLeafParams.Select(p => p + " != \"\""));
                    slots.Add("(" + presence + ", " + itemExpr + ")");
                    leafParams.AddRange(itemLeafParams);
                }
                return ("JsonArray(" + string.Join(", ", slots) + ")", leafParams);
            }
            default:   // string/integer/number/boolean scalar leaf
            {
                var paramName = UniqueName(nameHint + arraySlotSuffix, used);
                var expr = schema.JsonType switch
                {
                    "integer" or "number" => "JsonNumber(" + paramName + ")",
                    "boolean" => "JsonBool(" + paramName + ")",
                    _ => "JsonString(" + paramName + ")",
                };
                return (expr, new List<string> { paramName });
            }
        }
    }

    /// <summary>True when a body schema (or any of its nested properties/items) contains an
    /// array — used only to decide whether the "leave a slot empty to omit it" doc note applies.</summary>
    private static bool SchemaContainsArray(ApiSchema schema) => schema.JsonType switch
    {
        "array" => true,
        "object" => schema.Properties.Any(p => SchemaContainsArray(p.Schema)),
        _ => false,
    };

    /// <summary>A JSON object key (with trailing colon) as a C# string literal, e.g. for
    /// property name "custId" this returns the C# source text <c>"\"custId\":"</c>.</summary>
    private static string JsonKeyPrefixLit(string propertyName) => Lit("\"" + JsonEscapeText(propertyName) + "\":");

    /// <summary>Escapes the characters Lit() also escapes, without the surrounding quotes —
    /// used to build a JSON-safe fragment before Lit() re-escapes it for the C# literal.</summary>
    private static string JsonEscapeText(string s) => (s ?? "")
        .Replace("\\", "\\\\").Replace("\"", "\\\"")
        .Replace("\r", "\\r").Replace("\n", "\\n").Replace("\t", "\\t");

    // ---- Private HTTP core (emitted once per generated file) ----

    private static void AppendPrivateCore(
        StringBuilder sb, bool hasApiKeyHeader, bool hasApiKeyQuery, bool hasOAuth2, bool usesTypedBody, bool designerComponent)
    {
        // Designer mode swaps the static HttpClient for the instance-level _httpClient
        // (so Dispose can release it); the raw-string core is authored with _client and
        // rewritten here, keeping default output byte-identical to before.
        string Client(string text) => designerComponent ? text.Replace("_client.", "_httpClient.") : text;
        sb.AppendLine();
        sb.AppendLine(Client(CoreBuilders));
        if (usesTypedBody) sb.AppendLine(Client(JsonBodyHelpers));
        sb.AppendLine();
        sb.AppendLine(Client(SendOpen));
        if (hasApiKeyQuery) sb.AppendLine(Client(ApiKeyQuerySend));
        sb.AppendLine(Client(SendCallExecute));
        if (hasOAuth2) sb.AppendLine(Client(OAuth401Retry));
        sb.AppendLine(Client(SendClose));
        sb.AppendLine(Client(ExecuteOpen));
        if (hasOAuth2) sb.AppendLine(Client(OAuthExpiryCheck));
        sb.AppendLine(Client(ExecuteNewRequest));
        if (hasApiKeyHeader) sb.AppendLine(Client(ApiKeyHeaderSend));
        sb.AppendLine(Client(hasOAuth2 ? ExecuteAuthWithOAuth : ExecuteAuthWithoutOAuth));
        sb.AppendLine(Client(ExecuteTail));
        if (hasOAuth2) sb.AppendLine(Client(OAuthTokenMethods));
    }

    /// <summary>
    /// Standard Dispose pattern, emitted only in designerComponent mode where the
    /// instance-level HttpClient has resources to release. Robot Studio disposes
    /// component-tray components on teardown, which then also closes the HTTP connections.
    /// </summary>
    private const string DisposePattern =
"""
        private bool _disposed;

        /// <summary>Releases the instance HttpClient. Robot Studio disposes the component on teardown. Never throws.</summary>
        protected override void Dispose(bool disposing)
        {
            if (!_disposed)
            {
                if (disposing)
                {
                    _httpClient.Dispose();
                }
                _disposed = true;
            }
            base.Dispose(disposing);
        }
""";

    private const string CoreBuilders =
"""
        // ---- Private HTTP core (emitted once per file, never throws) ----

        private sealed class HeaderBuilder
        {
            internal List<KeyValuePair<string, string>> _headers = new();
            public HeaderBuilder WithHeader(string name, string value)
            {
                if (!string.IsNullOrEmpty(name) && !string.IsNullOrEmpty(value))
                    _headers.Add(new KeyValuePair<string, string>(name, value));
                return this;
            }
        }

        private HeaderBuilder NewHeaders() => new HeaderBuilder();

        private class QueryBuilder
        {
            private readonly List<string> _parts = new List<string>();
            public QueryBuilder Add(string name, string value)
            {
                if (!string.IsNullOrEmpty(name) && !string.IsNullOrEmpty(value))
                    _parts.Add(name + "=" + Uri.EscapeDataString(value));
                return this;
            }
            public override string ToString() => _parts.Count == 0 ? "" : "?" + string.Join("&", _parts);
        }

        private static QueryBuilder BuildQuery() { return new QueryBuilder(); }
""";

    /// <summary>Emitted only when at least one endpoint method flattened its body schema into
    /// typed parameters (see <see cref="TryFlattenBody"/>) — those methods' generated
    /// expressions call these to reassemble a JSON literal at runtime.</summary>
    private const string JsonBodyHelpers =
"""

        // ---- JSON body assembly (emitted once per file; used by methods with a flattened body) ----

        /// <summary>Encodes a value as a JSON string literal. Null becomes "". Never throws.</summary>
        private static string JsonString(string value)
        {
            var s = value ?? "";
            var sb = new StringBuilder(s.Length + 2);
            sb.Append('"');
            foreach (var c in s)
            {
                switch (c)
                {
                    case '"': sb.Append("\\\""); break;
                    case '\\': sb.Append("\\\\"); break;
                    case '\r': sb.Append("\\r"); break;
                    case '\n': sb.Append("\\n"); break;
                    case '\t': sb.Append("\\t"); break;
                    default:
                        if (c < ' ') sb.Append("\\u").Append(((int)c).ToString("x4"));
                        else sb.Append(c);
                        break;
                }
            }
            sb.Append('"');
            return sb.ToString();
        }

        /// <summary>Encodes a value as a JSON number literal; blank or unparsable input becomes 0. Never throws.</summary>
        private static string JsonNumber(string value) =>
            double.TryParse(value, System.Globalization.NumberStyles.Float, System.Globalization.CultureInfo.InvariantCulture, out var n)
                ? n.ToString(System.Globalization.CultureInfo.InvariantCulture)
                : "0";

        /// <summary>Encodes a value as a JSON boolean literal; anything other than a case-insensitive "true" becomes false. Never throws.</summary>
        private static string JsonBool(string value) =>
            string.Equals(value, "true", StringComparison.OrdinalIgnoreCase) ? "true" : "false";

        /// <summary>Joins the present slots (in schema order) into a JSON array literal; a slot whose
        /// fields were all left empty is omitted. Never throws.</summary>
        private static string JsonArray(params (bool Present, string Json)[] slots)
        {
            var parts = new List<string>();
            foreach (var slot in slots)
                if (slot.Present) parts.Add(slot.Json);
            return "[" + string.Join(",", parts) + "]";
        }
""";

    private const string SendOpen =
"""
        private bool Send(string httpMethod, string path, string query, string bodyJson,
            HeaderBuilder headers, out string responseJson, out int statusCode, out string message)
        {
            responseJson = "";
            statusCode = 0;
            if (string.IsNullOrEmpty(_baseUrl))
            {
                message = "Base URL is not set. Set the BaseUrl property first.";
                return false;
            }
""";

    private const string ApiKeyQuerySend =
"""
            if (!string.IsNullOrEmpty(_apiKeyQueryName))   // API-key-in-query auth is appended to every call
            {
                var keyValue = _apiKeyQueryName + "=" + Uri.EscapeDataString(_apiKeyQueryValue ?? "");
                query = string.IsNullOrEmpty(query) ? "?" + keyValue : query + "&" + keyValue;
            }
""";

    private const string SendCallExecute =
"""
            var uri = _baseUrl + path + (query ?? "");
            try
            {
                var ok = Execute(httpMethod, uri, bodyJson, headers, out responseJson, out statusCode, out message);
""";

    private const string OAuth401Retry =
"""
                if (ok && statusCode == 401 && _oauthTokenUrl != "" && TryRefreshOAuth2Token(out _))
                {
                    // one silent token refresh + single retry on 401 with client-credentials auth configured;
                    // on a failed retry, keep the failure message Execute already wrote
                    ok = Execute(httpMethod, uri, bodyJson, headers, out responseJson, out statusCode, out _);
                }
""";

    private const string SendClose =
"""
                return ok;
            }
            catch (Exception ex)
            {
                responseJson = "";
                statusCode = 0;
                _lastStatusCode = 0;
                message = httpMethod + " " + uri + " failed: " + ex.Message;
                return false;
            }
        }
""";

    private const string ExecuteOpen =
"""
        private bool Execute(string httpMethod, string uri, string bodyJson, HeaderBuilder headers,
            out string responseJson, out int statusCode, out string message)
        {
            responseJson = "";
            statusCode = 0;
            try
            {
""";

    private const string OAuthExpiryCheck =
"""
                if (_oauthTokenExpiresAtUtc <= System.DateTime.UtcNow && !TryRefreshOAuth2Token(out var oauthError))
                {
                    // only a hard failure when client-credentials auth is configured but the token endpoint fails
                    if (_oauthTokenUrl != "") { message = "OAuth2 token refresh failed: " + oauthError; return false; }
                }
""";

    private const string ExecuteNewRequest =
"""
                using var request = new HttpRequestMessage(new HttpMethod(httpMethod), uri);
""";

    private const string ApiKeyHeaderSend =
"""
                if (!string.IsNullOrEmpty(_apiKeyHeaderName) && !string.IsNullOrEmpty(_apiKeyHeaderValue))
                    request.Headers.TryAddWithoutValidation(_apiKeyHeaderName, _apiKeyHeaderValue);
""";

    private const string ExecuteAuthWithoutOAuth =
"""
                if (!string.IsNullOrEmpty(_authorizationHeader))
                    request.Headers.Authorization = AuthenticationHeaderValue.Parse(_authorizationHeader);
""";

    private const string ExecuteAuthWithOAuth =
"""
                if (!string.IsNullOrEmpty(_authorizationHeader))
                    request.Headers.Authorization = AuthenticationHeaderValue.Parse(_authorizationHeader);
                else if (!string.IsNullOrEmpty(_oauthAccessToken))
                    request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", _oauthAccessToken);
""";

    private const string ExecuteTail =
"""
                foreach (var h in headers._headers)
                    request.Headers.TryAddWithoutValidation(h.Key, h.Value);
                if (bodyJson != null)
                    request.Content = new StringContent(bodyJson, Encoding.UTF8, "application/json");
                using var cts = new System.Threading.CancellationTokenSource(TimeSpan.FromSeconds(_timeoutSeconds));
                using var response = _client.SendAsync(request, cts.Token).GetAwaiter().GetResult();
                statusCode = (int)response.StatusCode;
                _lastStatusCode = statusCode;
                responseJson = response.Content.ReadAsStringAsync().GetAwaiter().GetResult() ?? "";
                message = null;
                return true;
            }
            catch (Exception ex)
            {
                _lastStatusCode = 0;
                message = httpMethod + " " + uri + " failed: " + ex.Message;
                return false;
            }
        }
""";

    private const string OAuthTokenMethods =
"""
        private bool TryRefreshOAuth2Token(out string message)
        {
            if (_oauthTokenUrl == "" || _oauthTokenExpiresAtUtc > System.DateTime.UtcNow)
            { message = null; return true; }   // not configured, or cache still fresh
            try
            {
                using var request = new HttpRequestMessage(System.Net.Http.HttpMethod.Post, _oauthTokenUrl);
                var formFields = new List<KeyValuePair<string, string>>
                {
                    new KeyValuePair<string, string>("grant_type", "client_credentials"),
                    new KeyValuePair<string, string>("client_id", _oauthClientId),
                    new KeyValuePair<string, string>("client_secret", _oauthClientSecret),
                };
                if (_oauthScope != "") formFields.Add(new KeyValuePair<string, string>("scope", _oauthScope));
                request.Content = new FormUrlEncodedContent(formFields);
                using var cts = new System.Threading.CancellationTokenSource(TimeSpan.FromSeconds(_timeoutSeconds));
                using var response = _client.SendAsync(request, cts.Token).GetAwaiter().GetResult();
                var body = response.Content.ReadAsStringAsync().GetAwaiter().GetResult() ?? "";
                if ((int)response.StatusCode != 200)
                { message = "token endpoint returned " + (int)response.StatusCode; return false; }
                var token = ExtractJsonPropertyText(body, "access_token");
                if (token == "")
                { message = "token response had no access_token"; return false; }
                _oauthAccessToken = token;
                var expiresInText = ExtractJsonPropertyText(body, "expires_in");
                _ = int.TryParse(expiresInText, out var expiresIn);
                _oauthTokenExpiresAtUtc = System.DateTime.UtcNow.AddSeconds(
                    expiresIn > 0 ? expiresIn - 30 : 300);   // 30s safety margin; 5-minute default if unspecified
                message = null;
                return true;
            }
            catch (Exception ex)
            { message = ex.Message; return false; }
        }

        /// <summary>Minimal dependency-free JSON string-property extractor for the token endpoint response.</summary>
        private static string ExtractJsonPropertyText(string json, string propertyName)
        {
            if (json == null) return "";
            var marker = "\"" + propertyName + "\"";
            var i = json.IndexOf(marker, StringComparison.Ordinal);
            if (i < 0) return "";
            var colon = json.IndexOf(':', i + marker.Length);
            if (colon < 0) return "";
            var quote = json.IndexOf('"', colon + 1);
            if (quote < 0) return "";
            var sb = new StringBuilder();
            for (var j = quote + 1; j < json.Length; j++)
            {
                var c = json[j];
                if (c == '"') break;
                if (c == '\\' && j + 1 < json.Length) { sb.Append(json[++j]); continue; }
                sb.Append(c);
            }
            return sb.ToString();
        }
""";

    // ---- Escaping / normalize helpers ----

    /// <summary>
    /// Flattens a multi-line swagger text (an operation summary or the API description)
    /// into a single logical line BEFORE emission into XML docs and string literals —
    /// a raw "\n" would emit an XML doc continuation line without "///", or break a
    /// Description attribute literal.
    /// </summary>
    private static string Flatten(string? text)
    {
        var words = (text ?? "").Split(new[] { ' ', '\r', '\n', '\t' }, System.StringSplitOptions.RemoveEmptyEntries);
        return words.Length > 0 ? string.Join(" ", words) : "";
    }

    /// <summary>Greedy word-wrap of already-flattened (single-spaced) text into ///-comment
    /// lines; a single word longer than the width gets its own line.</summary>
    private static List<string> WrapWords(string text, int width)
    {
        var lines = new List<string>();
        if (text.Length == 0) return lines;
        var current = "";
        foreach (var word in text.Split(' '))
        {
            if (current.Length == 0) current = word;
            else if (current.Length + 1 + word.Length <= width) current += " " + word;
            else { lines.Add(current); current = word; }
        }
        if (current.Length > 0) lines.Add(current);
        return lines;
    }

    /// <summary>Quotes a value as a C# string literal for embedding in generated code (line breaks included, so multi-line summaries stay single-line).</summary>
    private static string Lit(string? s) =>
        "\"" + (s ?? "")
            .Replace("\\", "\\\\").Replace("\"", "\\\"")
            .Replace("\r", "\\r").Replace("\n", "\\n").Replace("\t", "\\t") + "\"";

    /// <summary>Escapes a value for use inside an XML doc comment.</summary>
    private static string Xml(string? s) => (s ?? "")
        .Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");

    // ---- Fallback csproj (makes the single .cs buildable standalone; zero packages) ----

    private const string FallbackProject =
"""
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0-windows;net10.0-windows</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>%Namespace%</AssemblyName>
    <RootNamespace>%Namespace%</RootNamespace>
    <Platforms>AnyCPU;x64</Platforms>
    <!-- Emit the XML doc file next to the DLL so the generated method docs are consumable -->
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <!-- Lets `dotnet build` of the generated project work on non-Windows machines too. -->
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

</Project>
""";
}