using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace RestCodeGenerator;

/// <summary>
/// Renders a parsed swagger document (plus an API name) into the complete generated
/// component: one self-contained `.cs` source text and the fallback `.csproj` text.
/// The emitted text follows the Task 4 template in
/// project-docs/plans/2026-08-31-swagger-rest-codegen.md — that template is the contract.
/// The template's verbatim blocks are kept as raw-string constants below; only the
/// endpoint methods, fields, and header comment are computed per document.
/// </summary>
public static class ComponentRenderer
{
    /// <param name="designerComponent">When true, the class derives from
    /// <c>System.ComponentModel.Component</c> and follows the Dispose pattern: the
    /// HttpClient becomes instance-level so Dispose can release it (Robot Studio
    /// disposes tray components on teardown). Default false keeps Script-component
    /// paste-in output with the shared static client.</param>
    public static (string FileNameBase, string Source, string Project) Render(SwaggerDoc doc, string apiName, bool designerComponent = false)
    {
        var root = MethodNameMapper.Pascalize(apiName) ?? "Api";
        var className = root + "RestUtils";
        var @namespace = root + "RestAutomation";

        // Scheme-conditional helpers are emitted only when the spec declares that kind.
        var hasApiKeyHeader = doc.SecuritySchemes.Any(s => s.Kind == "apiKeyHeader");
        var hasApiKeyQuery = doc.SecuritySchemes.Any(s => s.Kind == "apiKeyQuery");
        var hasOAuth2 = doc.SecuritySchemes.Any(s => s.Kind == "oauth2ClientCredentials");
        var unsupportedSchemes = doc.SecuritySchemes.Where(s => s.Kind == "unsupported").ToList();

        var sb = new StringBuilder();
        AppendFileHeader(sb, doc, unsupportedSchemes);
        AppendNamespaceAndClass(sb, doc, @namespace, className, designerComponent);
        AppendFields(sb, doc, hasApiKeyHeader, hasApiKeyQuery, hasOAuth2, designerComponent);
        sb.AppendLine();
        sb.AppendLine(AlwaysPresentHelpers(hasApiKeyHeader, hasApiKeyQuery, hasOAuth2));
        if (hasApiKeyHeader) sb.AppendLine("\n" + ApiKeyHeaderHelper);
        if (hasApiKeyQuery) sb.AppendLine("\n" + ApiKeyQueryHelper);
        if (hasOAuth2) sb.AppendLine("\n" + OAuth2Helper);
        AppendEndpointMethods(sb, doc);
        AppendPrivateCore(sb, hasApiKeyHeader, hasApiKeyQuery, hasOAuth2, designerComponent);
        if (designerComponent) sb.AppendLine("\n" + DisposePattern);
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return (className, sb.ToString(), FallbackProject.Replace("%Namespace%", @namespace));
    }

    // ---- Header comment / class declaration / fields ----

    private static void AppendFileHeader(StringBuilder sb, SwaggerDoc doc, List<SwaggerSecurityScheme> unsupported)
    {
        sb.Append("// <auto-generated>Generated by RestCodeGenerator from ")
          .Append(doc.Title ?? "Api").Append(" swagger ").Append(doc.Version ?? "1.0.0")
          .AppendLine(". Do not edit.</auto-generated>");
        sb.AppendLine("// Skipped operations (non-JSON bodies are not supported):");
        if (doc.SkippedOperations.Count == 0)
            sb.AppendLine("//   (none)");
        else
            foreach (var skipped in doc.SkippedOperations)
                sb.AppendLine("//   " + skipped);
        if (unsupported.Count > 0)
        {
            sb.AppendLine("// Unsupported authentication schemes (no helper generated — use SetBearerAuthentication");
            sb.AppendLine("//   or SetCustomAuthentication with a caller-managed token instead):");
            foreach (var scheme in unsupported)
                sb.AppendLine("//   " + scheme.Name);
        }
        sb.AppendLine();
    }

    private static void AppendNamespaceAndClass(
        StringBuilder sb, SwaggerDoc doc, string @namespace, string className, bool designerComponent)
    {
        var title = doc.Title ?? "Api";
        var version = doc.Version ?? "1.0.0";
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Net.Http;");
        sb.AppendLine("using System.Net.Http.Headers;");
        sb.AppendLine("using System.Text;");
        sb.AppendLine();
        sb.AppendLine("namespace " + @namespace);
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Generated REST client component for \"" + Xml(title) + "\" (" + Xml(title) + " " + version + ").");
        sb.AppendLine("    /// One method per operation in the source swagger file. Response bodies are");
        sb.AppendLine("    /// returned as raw JSON strings; parse them with Robot Studio's built-in JSON");
        sb.AppendLine("    /// methods. Every public method follows the Never-Throws Standard: success");
        sb.AppendLine("    /// returns true with message null; failure returns false with a reason.");
        sb.AppendLine("    /// Pass \"\" for any optional string parameter to omit it.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    [System.ComponentModel.Description(" +
                      Lit("Generated REST client for " + title + " (" + title + " " + version + "). Never throws.") + ")]");
        sb.AppendLine("    public class " + className +
                      (designerComponent ? " : System.ComponentModel.Component" : ""));
        sb.AppendLine("    {");
    }

    private static void AppendFields(
        StringBuilder sb, SwaggerDoc doc, bool hasApiKeyHeader, bool hasApiKeyQuery, bool hasOAuth2,
        bool designerComponent)
    {
        if (string.IsNullOrEmpty(doc.DefaultBaseUrl))
            sb.AppendLine("        private string _baseUrl = \"\";");
        else
            sb.AppendLine("        private string _baseUrl = " + Lit(doc.DefaultBaseUrl) + ";   // prefilled from the spec's base URL");
        sb.AppendLine("        private string _authorizationHeader = \"\";");
        if (hasApiKeyHeader)
        {
            sb.AppendLine("        private string _apiKeyHeaderName = \"\";      // API key sent as a named header on every call");
            sb.AppendLine("        private string _apiKeyHeaderValue = \"\";");
        }
        if (hasApiKeyQuery)
        {
            sb.AppendLine("        private string _apiKeyQueryName = \"\";       // API key appended to the query string of every call");
            sb.AppendLine("        private string _apiKeyQueryValue = \"\";");
        }
        if (hasOAuth2)
        {
            sb.AppendLine("        private string _oauthClientId = \"\";         // OAuth2 client-credentials configuration");
            sb.AppendLine("        private string _oauthClientSecret = \"\";");
            sb.AppendLine("        private string _oauthTokenUrl = \"\";");
            sb.AppendLine("        private string _oauthAccessToken = \"\";");
            sb.AppendLine("        private System.DateTime _oauthTokenExpiresAtUtc = System.DateTime.MinValue;");
        }
        sb.AppendLine("        private int _lastStatusCode;");
        sb.AppendLine("        private int _timeoutSeconds = 30;");
        if (designerComponent)
        {
            // instance-level client so the Dispose pattern below has something real to release
            sb.AppendLine("        private readonly HttpClient _httpClient = new HttpClient();");
        }
        else
        {
            sb.AppendLine("        private static readonly HttpClient _client = new HttpClient();");
        }
    }

    // ---- Always-present public helpers ----

    /// <summary>
    /// The helpers every generated component carries, regardless of declared schemes.
    /// The //[[…]] markers inside ClearAuthentication become a clear line only for the
    /// scheme-conditional fields that exist in the emitted file (dropped otherwise, so
    /// ClearAuthentication never references a field that was not emitted).
    /// </summary>
    private static string AlwaysPresentHelpers(bool hasApiKeyHeader, bool hasApiKeyQuery, bool hasOAuth2)
    {
        // Markers are matched WITHOUT a trailing newline so the replacement is CRLF-safe
        // (raw strings preserve the source file's line endings). When the scheme is not
        // declared, a comment line remains instead of a live statement.
        return AlwaysPresentHelpersCore
            .Replace("            //[[API_KEY_HEADER_CLEAR]]", hasApiKeyHeader
                ? "            _apiKeyHeaderName = \"\"; _apiKeyHeaderValue = \"\";"
                : "            // (no api-key-header scheme declared)")
            .Replace("            //[[API_KEY_QUERY_CLEAR]]", hasApiKeyQuery
                ? "            _apiKeyQueryName = \"\"; _apiKeyQueryValue = \"\";"
                : "            // (no api-key-query scheme declared)")
            .Replace("            //[[OAUTH_CLEAR]]", hasOAuth2
                ? "            _oauthAccessToken = \"\";"
                : "            // (no client-credentials oauth2 scheme declared)");
    }

    private const string AlwaysPresentHelpersCore =
"""
        // ---- Always-present helpers (never throws) ----

        /// <summary>Sets the base URL used for every request. Required when BaseUrl was templated in the source spec. Never throws.</summary>
        public bool SetBaseUrl(string url, out string message)
        {
            if (string.IsNullOrWhiteSpace(url)) { message = "SetBaseUrl: url must be a non-empty string."; return false; }
            _baseUrl = url.TrimEnd('/');
            message = null; return true;
        }

        /// <summary>Sets the Authorization header to "Bearer &lt;token&gt;". Never throws.</summary>
        public bool SetBearerAuthentication(string token, out string message)
        {
            if (string.IsNullOrWhiteSpace(token)) { message = "SetBearerAuthentication: token must be non-empty."; return false; }
            _authorizationHeader = "Bearer " + token.Trim();
            message = null; return true;
        }

        /// <summary>Sets the Authorization header to HTTP Basic. Never throws.</summary>
        public bool SetBasicAuthentication(string username, string password, out string message)
        {
            try
            {
                _authorizationHeader = "Basic " + Convert.ToBase64String(Encoding.UTF8.GetBytes((username ?? "") + ":" + (password ?? "")));
                message = null; return true;
            }
            catch (Exception ex)
            {
                _authorizationHeader = "";
                message = "SetBasicAuthentication: " + ex.Message; return false;
            }
        }

        /// <summary>Sets the Authorization header to an explicit value (e.g. an API key that arrives as the Authorization value). Never throws.</summary>
        public bool SetCustomAuthentication(string headerValue, out string message)
        {
            if (string.IsNullOrWhiteSpace(headerValue)) { message = "SetCustomAuthentication: headerValue must be non-empty."; return false; }
            _authorizationHeader = headerValue.Trim();
            message = null; return true;
        }

        /// <summary>Clears all configured authentication (Authorization header, API keys, cached OAuth2 token — the client-credentials configuration itself is kept). Never throws.</summary>
        public bool ClearAuthentication(out string message)
        {
            _authorizationHeader = "";
            //[[API_KEY_HEADER_CLEAR]]
            //[[API_KEY_QUERY_CLEAR]]
            //[[OAUTH_CLEAR]]
            message = null; return true;
        }

        /// <summary>Sets the request timeout in seconds (1–600). Never throws.</summary>
        public bool SetTimeoutSeconds(int seconds, out string message)
        {
            if (seconds < 1 || seconds > 600) { message = "SetTimeoutSeconds: seconds must be between 1 and 600."; return false; }
            _timeoutSeconds = seconds;
            message = null; return true;
        }

        /// <summary>The HTTP status code of the most recent endpoint call; 0 before the first call. Never throws.</summary>
        public int LastStatusCode
        {
            get { return _lastStatusCode; }
        }
""";

    // ---- Scheme-conditional auth helpers ----

    /// <summary>Emitted when the spec declares an apiKey scheme with `in: header`.</summary>
    private const string ApiKeyHeaderHelper =
"""
        /// <summary>Sets an API key sent as a named header on every call. Never throws.</summary>
        public bool SetApiKeyAuthentication(string name, string value, out string message)
        {
            if (string.IsNullOrWhiteSpace(name)) { message = "SetApiKeyAuthentication: name must be non-empty."; return false; }
            _apiKeyHeaderName = name.Trim();
            _apiKeyHeaderValue = value ?? "";
            message = null; return true;
        }
""";

    /// <summary>Emitted when the spec declares an apiKey scheme with `in: query`.</summary>
    private const string ApiKeyQueryHelper =
"""
        /// <summary>Sets an API key appended to the query string of every call. Never throws.</summary>
        public bool SetApiKeyQueryAuthentication(string name, string value, out string message)
        {
            if (string.IsNullOrWhiteSpace(name)) { message = "SetApiKeyQueryAuthentication: name must be non-empty."; return false; }
            _apiKeyQueryName = name.Trim();
            _apiKeyQueryValue = value ?? "";
            message = null; return true;
        }
""";

    /// <summary>Emitted when the spec declares an oauth2 scheme with the client-credentials (or "application") flow.</summary>
    private const string OAuth2Helper =
"""
        /// <summary>Configures OAuth2 client-credentials authentication. The access token is fetched on the
        /// next call, cached, and refreshed automatically when expired or after a single 401-then-retry. Never throws.</summary>
        public bool SetOAuth2ClientCredentials(string clientId, string clientSecret, string tokenUrl, out string message)
        {
            if (string.IsNullOrWhiteSpace(clientId) || string.IsNullOrWhiteSpace(clientSecret) || string.IsNullOrWhiteSpace(tokenUrl))
            { message = "SetOAuth2ClientCredentials: clientId, clientSecret, and tokenUrl must all be non-empty."; return false; }
            _oauthClientId = clientId.Trim();
            _oauthClientSecret = clientSecret;
            _oauthTokenUrl = tokenUrl.Trim();
            _oauthAccessToken = "";
            _oauthTokenExpiresAtUtc = System.DateTime.MinValue;
            message = null; return true;
        }
""";

    // ---- Endpoint methods (one per modeled swagger operation) ----

    private static void AppendEndpointMethods(StringBuilder sb, SwaggerDoc doc)
    {
        var names = MethodNameMapper.Map(doc.Operations);
        sb.AppendLine();
        sb.AppendLine("        // ---- Endpoint methods (one per usable swagger operation) ----");
        foreach (var op in doc.Operations)
            AppendEndpointMethod(sb, op, names[op]);
    }

    /// <summary>
    /// Emits one endpoint method: path params become chained <c>.Replace("{name}", …)</c>
    /// substitutions, query params a <c>BuildQuery().Add(…)</c> chain, header params a
    /// <c>WithHeader(…)</c> chain, and <c>bodyJson</c> appears only for body-carrying
    /// operations. All inputs are designers' strings; the never-throw HTTP core does the rest.
    /// </summary>
    private static void AppendEndpointMethod(StringBuilder sb, SwaggerOperation op, string name)
    {
        var used = new HashSet<string>();
        var paths = op.PathParams.Select(p => (Original: p.Name, Param: ParamName(p, used))).ToList();
        var queries = op.QueryParams.Select(p => (Original: p.Name, Param: ParamName(p, used))).ToList();
        var headers = op.HeaderParams.Select(p => (Original: p.Name, Param: ParamName(p, used))).ToList();

        // A multi-line swagger summary must be flattened to a single line here, before it
        // feeds either the XML doc comment (a raw "\n" would emit a continuation line
        // without "///") or the Description attribute (Lit also escapes, per defense in depth).
        var words = (op.Summary ?? "").Split(new[] { ' ', '\r', '\n', '\t' }, System.StringSplitOptions.RemoveEmptyEntries);
        var summary = words.Length > 0
            ? string.Join(" ", words)
            : "Performs the " + op.HttpMethod + " request on " + op.Path + ".";

        sb.AppendLine();
        sb.AppendLine("        /// <summary>" + Xml(summary) +
                      " Returns true if the HTTP call completed; check statusCode for 4xx/5xx. Never throws.</summary>");
        sb.AppendLine("        [System.ComponentModel.Description(" +
                      Lit(summary + " (" + op.HttpMethod + " " + op.Path + ")") + ")]");

        var signature = new List<string>();
        signature.AddRange(paths.Select(p => "string " + p.Param));
        signature.AddRange(queries.Select(p => "string " + p.Param));
        signature.AddRange(headers.Select(p => "string " + p.Param));
        if (op.HasBody)
            signature.Add("string bodyJson");
        signature.Add("out string responseJson");
        signature.Add("out int statusCode");
        signature.Add("out string message");

        sb.AppendLine("        public bool " + name + "(" + string.Join(", ", signature) + ")");
        sb.AppendLine("        {");

        sb.Append("            var path = " + Lit(op.Path));
        foreach (var p in paths)
            sb.Append(".Replace(" + Lit("{" + p.Original + "}") + ", Uri.EscapeDataString(" + p.Param + " ?? \"\"))");
        sb.AppendLine(";");

        if (queries.Count == 1)
        {
            sb.AppendLine("            var query = BuildQuery().Add(" + Lit(queries[0].Original) + ", " + queries[0].Param + ").ToString();");
        }
        else if (queries.Count > 1)
        {
            sb.AppendLine("            var query = BuildQuery()");
            foreach (var q in queries)
                sb.AppendLine("                .Add(" + Lit(q.Original) + ", " + q.Param + ")");
            sb.AppendLine("                .ToString();");
        }

        var queryArg = queries.Count > 0 ? "query" : "BuildQuery().ToString()";
        var bodyArg = op.HasBody ? "bodyJson" : "null";
        sb.Append("            return Send(" + Lit(op.HttpMethod) + ", path, " + queryArg + ", " + bodyArg + ", ");
        if (headers.Count == 0)
        {
            sb.AppendLine("NewHeaders(), out responseJson, out statusCode, out message);");
        }
        else if (headers.Count == 1)
        {
            sb.AppendLine("NewHeaders().WithHeader(" + Lit(headers[0].Original) + ", " + headers[0].Param + "), out responseJson, out statusCode, out message);");
        }
        else
        {
            sb.AppendLine("NewHeaders()");
            for (var i = 0; i < headers.Count; i++)
            {
                var line = "                .WithHeader(" + Lit(headers[i].Original) + ", " + headers[i].Param + ")";
                sb.AppendLine(i == headers.Count - 1
                    ? line + ", out responseJson, out statusCode, out message);"
                    : line);
            }
        }
        sb.AppendLine("        }");
    }

    /// <summary>Camelizes a swagger parameter name into a C# identifier, unique within one method.</summary>
    private static string ParamName(SwaggerParameter p, HashSet<string> used)
    {
        var pascal = MethodNameMapper.Pascalize(p.Name) ?? "Param";
        var name = char.ToLowerInvariant(pascal[0]) + pascal[1..];
        var candidate = name;
        var suffix = 2;
        while (!used.Add(candidate))
            candidate = name + suffix++;
        return candidate;
    }

    // ---- Private HTTP core (emitted once per generated file) ----

    private static void AppendPrivateCore(
        StringBuilder sb, bool hasApiKeyHeader, bool hasApiKeyQuery, bool hasOAuth2, bool designerComponent)
    {
        // Designer mode swaps the static HttpClient for the instance-level _httpClient
        // (so Dispose can release it); the raw-string core is authored with _client and
        // rewritten here, keeping default output byte-identical to before.
        string Client(string text) => designerComponent ? text.Replace("_client.", "_httpClient.") : text;
        sb.AppendLine();
        sb.AppendLine(Client(CoreBuilders));
        sb.AppendLine();
        sb.AppendLine(Client(SendOpen));
        if (hasApiKeyQuery) sb.AppendLine(Client(ApiKeyQuerySend));
        sb.AppendLine(Client(SendCallExecute));
        if (hasOAuth2) sb.AppendLine(Client(OAuth401Retry));
        sb.AppendLine(Client(SendClose));
        sb.AppendLine(Client(ExecuteOpen));
        if (hasOAuth2) sb.AppendLine(Client(OAuthExpiryCheck));
        sb.AppendLine(Client(ExecuteNewRequest));
        if (hasApiKeyHeader) sb.AppendLine(Client(ApiKeyHeaderSend));
        sb.AppendLine(Client(hasOAuth2 ? ExecuteAuthWithOAuth : ExecuteAuthWithoutOAuth));
        sb.AppendLine(Client(ExecuteTail));
        if (hasOAuth2) sb.AppendLine(Client(OAuthTokenMethods));
    }

    /// <summary>
    /// Standard Dispose pattern, emitted only in designerComponent mode where the
    /// instance-level HttpClient has resources to release. Robot Studio disposes
    /// component-tray components on teardown, which then also closes the HTTP connections.
    /// </summary>
    private const string DisposePattern =
"""
        private bool _disposed;

        /// <summary>Releases the instance HttpClient. Robot Studio disposes the component on teardown. Never throws.</summary>
        protected override void Dispose(bool disposing)
        {
            if (!_disposed)
            {
                if (disposing)
                {
                    _httpClient.Dispose();
                }
                _disposed = true;
            }
            base.Dispose(disposing);
        }
""";

    private const string CoreBuilders =
"""
        // ---- Private HTTP core (emitted once per file, never throws) ----

        private sealed class HeaderBuilder
        {
            internal List<KeyValuePair<string, string>> _headers = new();
            public HeaderBuilder WithHeader(string name, string value)
            {
                if (!string.IsNullOrEmpty(name) && !string.IsNullOrEmpty(value))
                    _headers.Add(new KeyValuePair<string, string>(name, value));
                return this;
            }
        }

        private HeaderBuilder NewHeaders() => new HeaderBuilder();

        private class QueryBuilder
        {
            private readonly List<string> _parts = new List<string>();
            public QueryBuilder Add(string name, string value)
            {
                if (!string.IsNullOrEmpty(name) && !string.IsNullOrEmpty(value))
                    _parts.Add(name + "=" + Uri.EscapeDataString(value));
                return this;
            }
            public override string ToString() => _parts.Count == 0 ? "" : "?" + string.Join("&", _parts);
        }

        private static QueryBuilder BuildQuery() { return new QueryBuilder(); }
""";

    private const string SendOpen =
"""
        private bool Send(string httpMethod, string path, string query, string bodyJson,
            HeaderBuilder headers, out string responseJson, out int statusCode, out string message)
        {
            responseJson = "";
            statusCode = 0;
            if (string.IsNullOrEmpty(_baseUrl))
            {
                message = "Base URL is not set. Call SetBaseUrl first.";
                return false;
            }
""";

    private const string ApiKeyQuerySend =
"""
            if (!string.IsNullOrEmpty(_apiKeyQueryName))   // API-key-in-query auth is appended to every call
            {
                var keyValue = _apiKeyQueryName + "=" + Uri.EscapeDataString(_apiKeyQueryValue ?? "");
                query = string.IsNullOrEmpty(query) ? "?" + keyValue : query + "&" + keyValue;
            }
""";

    private const string SendCallExecute =
"""
            var uri = _baseUrl + path + (query ?? "");
            try
            {
                var ok = Execute(httpMethod, uri, bodyJson, headers, out responseJson, out statusCode, out message);
""";

    private const string OAuth401Retry =
"""
                if (ok && statusCode == 401 && _oauthTokenUrl != "" && TryRefreshOAuth2Token(out _))
                {
                    // one silent token refresh + single retry on 401 with client-credentials auth configured;
                    // on a failed retry, keep the failure message Execute already wrote
                    ok = Execute(httpMethod, uri, bodyJson, headers, out responseJson, out statusCode, out _);
                }
""";

    private const string SendClose =
"""
                return ok;
            }
            catch (Exception ex)
            {
                responseJson = "";
                statusCode = 0;
                _lastStatusCode = 0;
                message = httpMethod + " " + uri + " failed: " + ex.Message;
                return false;
            }
        }
""";

    private const string ExecuteOpen =
"""
        private bool Execute(string httpMethod, string uri, string bodyJson, HeaderBuilder headers,
            out string responseJson, out int statusCode, out string message)
        {
            responseJson = "";
            statusCode = 0;
            try
            {
""";

    private const string OAuthExpiryCheck =
"""
                if (_oauthTokenExpiresAtUtc <= System.DateTime.UtcNow && !TryRefreshOAuth2Token(out var oauthError))
                {
                    // only a hard failure when client-credentials auth is configured but the token endpoint fails
                    if (_oauthTokenUrl != "") { message = "OAuth2 token refresh failed: " + oauthError; return false; }
                }
""";

    private const string ExecuteNewRequest =
"""
                using var request = new HttpRequestMessage(new HttpMethod(httpMethod), uri);
""";

    private const string ApiKeyHeaderSend =
"""
                if (!string.IsNullOrEmpty(_apiKeyHeaderName) && !string.IsNullOrEmpty(_apiKeyHeaderValue))
                    request.Headers.TryAddWithoutValidation(_apiKeyHeaderName, _apiKeyHeaderValue);
""";

    private const string ExecuteAuthWithoutOAuth =
"""
                if (!string.IsNullOrEmpty(_authorizationHeader))
                    request.Headers.Authorization = AuthenticationHeaderValue.Parse(_authorizationHeader);
""";

    private const string ExecuteAuthWithOAuth =
"""
                if (!string.IsNullOrEmpty(_authorizationHeader))
                    request.Headers.Authorization = AuthenticationHeaderValue.Parse(_authorizationHeader);
                else if (!string.IsNullOrEmpty(_oauthAccessToken))
                    request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", _oauthAccessToken);
""";

    private const string ExecuteTail =
"""
                foreach (var h in headers._headers)
                    request.Headers.TryAddWithoutValidation(h.Key, h.Value);
                if (bodyJson != null)
                    request.Content = new StringContent(bodyJson, Encoding.UTF8, "application/json");
                using var cts = new System.Threading.CancellationTokenSource(TimeSpan.FromSeconds(_timeoutSeconds));
                using var response = _client.SendAsync(request, cts.Token).GetAwaiter().GetResult();
                statusCode = (int)response.StatusCode;
                _lastStatusCode = statusCode;
                responseJson = response.Content.ReadAsStringAsync().GetAwaiter().GetResult() ?? "";
                message = null;
                return true;
            }
            catch (Exception ex)
            {
                _lastStatusCode = 0;
                message = httpMethod + " " + uri + " failed: " + ex.Message;
                return false;
            }
        }
""";

    private const string OAuthTokenMethods =
"""
        private bool TryRefreshOAuth2Token(out string message)
        {
            if (_oauthTokenUrl == "" || _oauthTokenExpiresAtUtc > System.DateTime.UtcNow)
            { message = null; return true; }   // not configured, or cache still fresh
            try
            {
                using var request = new HttpRequestMessage(System.Net.Http.HttpMethod.Post, _oauthTokenUrl);
                request.Content = new FormUrlEncodedContent(new[]
                {
                    new KeyValuePair<string, string>("grant_type", "client_credentials"),
                    new KeyValuePair<string, string>("client_id", _oauthClientId),
                    new KeyValuePair<string, string>("client_secret", _oauthClientSecret),
                });
                using var cts = new System.Threading.CancellationTokenSource(TimeSpan.FromSeconds(_timeoutSeconds));
                using var response = _client.SendAsync(request, cts.Token).GetAwaiter().GetResult();
                var body = response.Content.ReadAsStringAsync().GetAwaiter().GetResult() ?? "";
                if ((int)response.StatusCode != 200)
                { message = "token endpoint returned " + (int)response.StatusCode; return false; }
                var token = ExtractJsonPropertyText(body, "access_token");
                if (token == "")
                { message = "token response had no access_token"; return false; }
                _oauthAccessToken = token;
                var expiresInText = ExtractJsonPropertyText(body, "expires_in");
                _ = int.TryParse(expiresInText, out var expiresIn);
                _oauthTokenExpiresAtUtc = System.DateTime.UtcNow.AddSeconds(
                    expiresIn > 0 ? expiresIn - 30 : 300);   // 30s safety margin; 5-minute default if unspecified
                message = null;
                return true;
            }
            catch (Exception ex)
            { message = ex.Message; return false; }
        }

        /// <summary>Minimal dependency-free JSON string-property extractor for the token endpoint response.</summary>
        private static string ExtractJsonPropertyText(string json, string propertyName)
        {
            if (json == null) return "";
            var marker = "\"" + propertyName + "\"";
            var i = json.IndexOf(marker, StringComparison.Ordinal);
            if (i < 0) return "";
            var colon = json.IndexOf(':', i + marker.Length);
            if (colon < 0) return "";
            var quote = json.IndexOf('"', colon + 1);
            if (quote < 0) return "";
            var sb = new StringBuilder();
            for (var j = quote + 1; j < json.Length; j++)
            {
                var c = json[j];
                if (c == '"') break;
                if (c == '\\' && j + 1 < json.Length) { sb.Append(json[++j]); continue; }
                sb.Append(c);
            }
            return sb.ToString();
        }
""";

    // ---- Escaping helpers ----

    /// <summary>Quotes a value as a C# string literal for embedding in generated code (line breaks included, so multi-line summaries stay single-line).</summary>
    private static string Lit(string? s) =>
        "\"" + (s ?? "")
            .Replace("\\", "\\\\").Replace("\"", "\\\"")
            .Replace("\r", "\\r").Replace("\n", "\\n").Replace("\t", "\\t") + "\"";

    /// <summary>Escapes a value for use inside an XML doc comment.</summary>
    private static string Xml(string? s) => (s ?? "")
        .Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");

    // ---- Fallback csproj (makes the single .cs buildable standalone; zero packages) ----

    private const string FallbackProject =
"""
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0-windows;net10.0-windows</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>%Namespace%</AssemblyName>
    <RootNamespace>%Namespace%</RootNamespace>
    <Platforms>AnyCPU;x64</Platforms>
    <!-- Emit the XML doc file next to the DLL so the generated method docs are consumable -->
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <!-- Lets `dotnet build` of the generated project work on non-Windows machines too. -->
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

</Project>
""";
}